// seed/seedData.js
// Sample data used to populate the database for development/demo purposes.

const users = [
  {
    name: 'Admin User',
    email: 'admin@store.com',
    password: 'admin123', // will be hashed by the User model's pre-save hook
    role: 'admin',
  },
  {
    name: 'Test Customer',
    email: 'customer@store.com',
    password: 'customer123',
    role: 'customer',
  },
];

const products = [
  {
    name: 'Wireless Bluetooth Headphones',
    description: 'Over-ear wireless headphones with active noise cancellation, 30-hour battery life, and deep bass sound.',
    price: 2499,
    category: 'Electronics',
    brand: 'SoundWave',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500',
    stock: 25,
    rating: 4.5,
    numReviews: 34,
  },
  {
    name: 'Smart Fitness Watch',
    description: 'Track your heart rate, sleep, and workouts with this waterproof smart watch featuring a 7-day battery life.',
    price: 3299,
    category: 'Electronics',
    brand: 'FitTrack',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500',
    stock: 18,
    rating: 4.2,
    numReviews: 21,
  },
  {
    name: 'Men\'s Running Shoes',
    description: 'Lightweight breathable running shoes with cushioned soles, ideal for daily runs and gym workouts.',
    price: 1899,
    category: 'Footwear',
    brand: 'RunFast',
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
    stock: 40,
    rating: 4.0,
    numReviews: 56,
  },
  {
    name: 'Classic Cotton T-Shirt',
    description: '100% pure cotton crew-neck t-shirt available in multiple colors. Comfortable everyday wear.',
    price: 499,
    category: 'Clothing',
    brand: 'UrbanStyle',
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500',
    stock: 100,
    rating: 4.3,
    numReviews: 78,
  },
  {
    name: 'Stainless Steel Water Bottle',
    description: 'Insulated 1-liter water bottle that keeps drinks cold for 24 hours and hot for 12 hours.',
    price: 699,
    category: 'Home & Kitchen',
    brand: 'HydroLife',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=500',
    stock: 60,
    rating: 4.6,
    numReviews: 45,
  },
  {
    name: 'Ergonomic Office Chair',
    description: 'Adjustable-height mesh office chair with lumbar support for all-day comfort while working from home.',
    price: 6999,
    category: 'Furniture',
    brand: 'ComfortPro',
    image: 'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=500',
    stock: 12,
    rating: 4.4,
    numReviews: 19,
  },
  {
    name: '4K Ultra HD Smart TV - 43 inch',
    description: 'Crystal-clear 4K display with built-in streaming apps, voice remote, and slim bezel design.',
    price: 24999,
    category: 'Electronics',
    brand: 'VisionMax',
    image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500',
    stock: 8,
    rating: 4.7,
    numReviews: 63,
  },
  {
    name: 'Non-Stick Cookware Set (5 Pieces)',
    description: 'Durable non-stick cookware set including frying pan, saucepan, and wok, safe for all stovetops.',
    price: 2199,
    category: 'Home & Kitchen',
    brand: 'ChefPro',
    image: 'https://images.unsplash.com/photo-1584990347449-a5d9f800a783?w=500',
    stock: 20,
    rating: 4.1,
    numReviews: 27,
  },
  {
    name: 'Leather Laptop Backpack',
    description: 'Water-resistant backpack with padded laptop compartment, USB charging port, and anti-theft zippers.',
    price: 1599,
    category: 'Accessories',
    brand: 'TravelGear',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500',
    stock: 33,
    rating: 4.5,
    numReviews: 41,
  },
  {
    name: 'Yoga Mat with Carry Strap',
    description: 'Extra-thick non-slip yoga mat, eco-friendly material, includes carry strap for easy transport.',
    price: 899,
    category: 'Sports & Fitness',
    brand: 'ZenFit',
    image: 'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=500',
    stock: 50,
    rating: 4.3,
    numReviews: 38,
  },
  {
    name: 'Wireless Mechanical Keyboard',
    description: 'RGB backlit mechanical keyboard with hot-swappable switches and Bluetooth + USB-C connectivity.',
    price: 3499,
    category: 'Electronics',
    brand: 'KeyMaster',
    image: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=500',
    stock: 15,
    rating: 4.6,
    numReviews: 29,
  },
  {
    name: 'Women\'s Denim Jacket',
    description: 'Classic fit denim jacket with button closure, perfect for layering in any season.',
    price: 1799,
    category: 'Clothing',
    brand: 'UrbanStyle',
    image: 'https://images.unsplash.com/photo-1601333144130-8cbb312386b6?w=500',
    stock: 28,
    rating: 4.2,
    numReviews: 22,
  },
];

module.exports = { users, products };
